// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.1
// source: proto/dataplane.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Optional: client pre-computed hash for verification
	ExpectedHash  *string `protobuf:"bytes,2,opt,name=expected_hash,json=expectedHash,proto3,oneof" json:"expected_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkRequest) Reset() {
	*x = PutChunkRequest{}
	mi := &file_proto_dataplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkRequest) ProtoMessage() {}

func (x *PutChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkRequest.ProtoReflect.Descriptor instead.
func (*PutChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{0}
}

func (x *PutChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PutChunkRequest) GetExpectedHash() string {
	if x != nil && x.ExpectedHash != nil {
		return *x.ExpectedHash
	}
	return ""
}

type PutChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // CAS address (blake3 hash)
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Deduplicated  bool                   `protobuf:"varint,3,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"` // Whether dedup was hit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkResponse) Reset() {
	*x = PutChunkResponse{}
	mi := &file_proto_dataplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkResponse) ProtoMessage() {}

func (x *PutChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkResponse.ProtoReflect.Descriptor instead.
func (*PutChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{1}
}

func (x *PutChunkResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PutChunkResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PutChunkResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type GetChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_proto_dataplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{2}
}

func (x *GetChunkRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_proto_dataplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{3}
}

func (x *GetChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HasChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasChunkRequest) Reset() {
	*x = HasChunkRequest{}
	mi := &file_proto_dataplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasChunkRequest) ProtoMessage() {}

func (x *HasChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasChunkRequest.ProtoReflect.Descriptor instead.
func (*HasChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{4}
}

func (x *HasChunkRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type HasChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Size          *uint64                `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasChunkResponse) Reset() {
	*x = HasChunkResponse{}
	mi := &file_proto_dataplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasChunkResponse) ProtoMessage() {}

func (x *HasChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasChunkResponse.ProtoReflect.Descriptor instead.
func (*HasChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{5}
}

func (x *HasChunkResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *HasChunkResponse) GetSize() uint64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type DeleteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkRequest) Reset() {
	*x = DeleteChunkRequest{}
	mi := &file_proto_dataplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkRequest) ProtoMessage() {}

func (x *DeleteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteChunkRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type DeleteChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunkResponse) Reset() {
	*x = DeleteChunkResponse{}
	mi := &file_proto_dataplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunkResponse) ProtoMessage() {}

func (x *DeleteChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunkResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteChunkResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type PutFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PutFileRequest_Metadata
	//	*PutFileRequest_Chunk
	Payload       isPutFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileRequest) Reset() {
	*x = PutFileRequest{}
	mi := &file_proto_dataplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileRequest) ProtoMessage() {}

func (x *PutFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileRequest.ProtoReflect.Descriptor instead.
func (*PutFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{8}
}

func (x *PutFileRequest) GetPayload() isPutFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutFileRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Payload.(*PutFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *PutFileRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*PutFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isPutFileRequest_Payload interface {
	isPutFileRequest_Payload()
}

type PutFileRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type PutFileRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*PutFileRequest_Metadata) isPutFileRequest_Payload() {}

func (*PutFileRequest_Chunk) isPutFileRequest_Payload() {}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ContentType   *string                `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_dataplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{9}
}

func (x *FileMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMetadata) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

type PutFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestHash  string                 `protobuf:"bytes,1,opt,name=manifest_hash,json=manifestHash,proto3" json:"manifest_hash,omitempty"` // CAS address of file manifest
	ChunkHashes   []string               `protobuf:"bytes,2,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`    // All chunk hashes
	TotalSize     uint64                 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	ChunkCount    uint32                 `protobuf:"varint,4,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	DedupRatio    float64                `protobuf:"fixed64,5,opt,name=dedup_ratio,json=dedupRatio,proto3" json:"dedup_ratio,omitempty"` // Deduplication ratio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutFileResponse) Reset() {
	*x = PutFileResponse{}
	mi := &file_proto_dataplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutFileResponse) ProtoMessage() {}

func (x *PutFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutFileResponse.ProtoReflect.Descriptor instead.
func (*PutFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{10}
}

func (x *PutFileResponse) GetManifestHash() string {
	if x != nil {
		return x.ManifestHash
	}
	return ""
}

func (x *PutFileResponse) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

func (x *PutFileResponse) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *PutFileResponse) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *PutFileResponse) GetDedupRatio() float64 {
	if x != nil {
		return x.DedupRatio
	}
	return 0
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestHash  string                 `protobuf:"bytes,1,opt,name=manifest_hash,json=manifestHash,proto3" json:"manifest_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_dataplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileRequest) GetManifestHash() string {
	if x != nil {
		return x.ManifestHash
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_dataplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{12}
}

func (x *GetFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_dataplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSecs    uint64                 `protobuf:"varint,3,opt,name=uptime_secs,json=uptimeSecs,proto3" json:"uptime_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_dataplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSecs() uint64 {
	if x != nil {
		return x.UptimeSecs
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_dataplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{15}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalChunks   uint64                 `protobuf:"varint,1,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	UniqueSize    uint64                 `protobuf:"varint,3,opt,name=unique_size,json=uniqueSize,proto3" json:"unique_size,omitempty"` // Actual size after dedup
	DedupRatio    float64                `protobuf:"fixed64,4,opt,name=dedup_ratio,json=dedupRatio,proto3" json:"dedup_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_dataplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{16}
}

func (x *StatsResponse) GetTotalChunks() uint64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *StatsResponse) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *StatsResponse) GetUniqueSize() uint64 {
	if x != nil {
		return x.UniqueSize
	}
	return 0
}

func (x *StatsResponse) GetDedupRatio() float64 {
	if x != nil {
		return x.DedupRatio
	}
	return 0
}

type ScrubRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: only verify specific hashes (empty = full scrub)
	Hashes        []string `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrubRequest) Reset() {
	*x = ScrubRequest{}
	mi := &file_proto_dataplane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrubRequest) ProtoMessage() {}

func (x *ScrubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrubRequest.ProtoReflect.Descriptor instead.
func (*ScrubRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{17}
}

func (x *ScrubRequest) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type ScrubResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalObjects     uint64                 `protobuf:"varint,1,opt,name=total_objects,json=totalObjects,proto3" json:"total_objects,omitempty"`
	ValidObjects     uint64                 `protobuf:"varint,2,opt,name=valid_objects,json=validObjects,proto3" json:"valid_objects,omitempty"`
	CorruptedObjects uint64                 `protobuf:"varint,3,opt,name=corrupted_objects,json=corruptedObjects,proto3" json:"corrupted_objects,omitempty"`
	MissingObjects   uint64                 `protobuf:"varint,4,opt,name=missing_objects,json=missingObjects,proto3" json:"missing_objects,omitempty"`
	TotalSize        uint64                 `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	DurationMs       uint64                 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Errors           []*ScrubError          `protobuf:"bytes,7,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScrubResponse) Reset() {
	*x = ScrubResponse{}
	mi := &file_proto_dataplane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrubResponse) ProtoMessage() {}

func (x *ScrubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrubResponse.ProtoReflect.Descriptor instead.
func (*ScrubResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{18}
}

func (x *ScrubResponse) GetTotalObjects() uint64 {
	if x != nil {
		return x.TotalObjects
	}
	return 0
}

func (x *ScrubResponse) GetValidObjects() uint64 {
	if x != nil {
		return x.ValidObjects
	}
	return 0
}

func (x *ScrubResponse) GetCorruptedObjects() uint64 {
	if x != nil {
		return x.CorruptedObjects
	}
	return 0
}

func (x *ScrubResponse) GetMissingObjects() uint64 {
	if x != nil {
		return x.MissingObjects
	}
	return 0
}

func (x *ScrubResponse) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ScrubResponse) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ScrubResponse) GetErrors() []*ScrubError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ScrubError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ErrorType     string                 `protobuf:"bytes,2,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"` // "corrupted", "missing", "io_error"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrubError) Reset() {
	*x = ScrubError{}
	mi := &file_proto_dataplane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrubError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrubError) ProtoMessage() {}

func (x *ScrubError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrubError.ProtoReflect.Descriptor instead.
func (*ScrubError) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{19}
}

func (x *ScrubError) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ScrubError) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *ScrubError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: pagination
	Cursor        *string `protobuf:"bytes,1,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	Limit         *uint32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_proto_dataplane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{20}
}

func (x *ListObjectsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

func (x *ListObjectsRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ListObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*ObjectInfo          `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"` // Empty if no more
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_proto_dataplane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{21}
}

func (x *ListObjectsResponse) GetObjects() []*ObjectInfo {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListObjectsResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

type ObjectInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hash  string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size  uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Creation timestamp for GC grace period filtering
	CreatedAtUnix *int64 `protobuf:"varint,3,opt,name=created_at_unix,json=createdAtUnix,proto3,oneof" json:"created_at_unix,omitempty"` // Unix timestamp in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectInfo) Reset() {
	*x = ObjectInfo{}
	mi := &file_proto_dataplane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInfo) ProtoMessage() {}

func (x *ObjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dataplane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInfo.ProtoReflect.Descriptor instead.
func (*ObjectInfo) Descriptor() ([]byte, []int) {
	return file_proto_dataplane_proto_rawDescGZIP(), []int{22}
}

func (x *ObjectInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ObjectInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectInfo) GetCreatedAtUnix() int64 {
	if x != nil && x.CreatedAtUnix != nil {
		return *x.CreatedAtUnix
	}
	return 0
}

var File_proto_dataplane_proto protoreflect.FileDescriptor

const file_proto_dataplane_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dataplane.proto\x12\x15mnemonas.dataplane.v1\"a\n" +
	"\x0fPutChunkRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12(\n" +
	"\rexpected_hash\x18\x02 \x01(\tH\x00R\fexpectedHash\x88\x01\x01B\x10\n" +
	"\x0e_expected_hash\"^\n" +
	"\x10PutChunkResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\"\n" +
	"\fdeduplicated\x18\x03 \x01(\bR\fdeduplicated\"%\n" +
	"\x0fGetChunkRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"&\n" +
	"\x10GetChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"%\n" +
	"\x0fHasChunkRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"L\n" +
	"\x10HasChunkResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x17\n" +
	"\x04size\x18\x02 \x01(\x04H\x00R\x04size\x88\x01\x01B\a\n" +
	"\x05_size\"(\n" +
	"\x12DeleteChunkRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"/\n" +
	"\x13DeleteChunkResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"v\n" +
	"\x0ePutFileRequest\x12A\n" +
	"\bmetadata\x18\x01 \x01(\v2#.mnemonas.dataplane.v1.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"[\n" +
	"\fFileMetadata\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12&\n" +
	"\fcontent_type\x18\x02 \x01(\tH\x00R\vcontentType\x88\x01\x01B\x0f\n" +
	"\r_content_type\"\xba\x01\n" +
	"\x0fPutFileResponse\x12#\n" +
	"\rmanifest_hash\x18\x01 \x01(\tR\fmanifestHash\x12!\n" +
	"\fchunk_hashes\x18\x02 \x03(\tR\vchunkHashes\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x04R\ttotalSize\x12\x1f\n" +
	"\vchunk_count\x18\x04 \x01(\rR\n" +
	"chunkCount\x12\x1f\n" +
	"\vdedup_ratio\x18\x05 \x01(\x01R\n" +
	"dedupRatio\"5\n" +
	"\x0eGetFileRequest\x12#\n" +
	"\rmanifest_hash\x18\x01 \x01(\tR\fmanifestHash\"%\n" +
	"\x0fGetFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x0f\n" +
	"\rHealthRequest\"e\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vuptime_secs\x18\x03 \x01(\x04R\n" +
	"uptimeSecs\"\x0e\n" +
	"\fStatsRequest\"\x93\x01\n" +
	"\rStatsResponse\x12!\n" +
	"\ftotal_chunks\x18\x01 \x01(\x04R\vtotalChunks\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\x12\x1f\n" +
	"\vunique_size\x18\x03 \x01(\x04R\n" +
	"uniqueSize\x12\x1f\n" +
	"\vdedup_ratio\x18\x04 \x01(\x01R\n" +
	"dedupRatio\"&\n" +
	"\fScrubRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"\xaa\x02\n" +
	"\rScrubResponse\x12#\n" +
	"\rtotal_objects\x18\x01 \x01(\x04R\ftotalObjects\x12#\n" +
	"\rvalid_objects\x18\x02 \x01(\x04R\fvalidObjects\x12+\n" +
	"\x11corrupted_objects\x18\x03 \x01(\x04R\x10corruptedObjects\x12'\n" +
	"\x0fmissing_objects\x18\x04 \x01(\x04R\x0emissingObjects\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x04R\ttotalSize\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x04R\n" +
	"durationMs\x129\n" +
	"\x06errors\x18\a \x03(\v2!.mnemonas.dataplane.v1.ScrubErrorR\x06errors\"Y\n" +
	"\n" +
	"ScrubError\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"error_type\x18\x02 \x01(\tR\terrorType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"a\n" +
	"\x12ListObjectsRequest\x12\x1b\n" +
	"\x06cursor\x18\x01 \x01(\tH\x00R\x06cursor\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\rH\x01R\x05limit\x88\x01\x01B\t\n" +
	"\a_cursorB\b\n" +
	"\x06_limit\"\x88\x01\n" +
	"\x13ListObjectsResponse\x12;\n" +
	"\aobjects\x18\x01 \x03(\v2!.mnemonas.dataplane.v1.ObjectInfoR\aobjects\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"u\n" +
	"\n" +
	"ObjectInfo\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12+\n" +
	"\x0fcreated_at_unix\x18\x03 \x01(\x03H\x00R\rcreatedAtUnix\x88\x01\x01B\x12\n" +
	"\x10_created_at_unix2\xa5\a\n" +
	"\tDataPlane\x12[\n" +
	"\bPutChunk\x12&.mnemonas.dataplane.v1.PutChunkRequest\x1a'.mnemonas.dataplane.v1.PutChunkResponse\x12[\n" +
	"\bGetChunk\x12&.mnemonas.dataplane.v1.GetChunkRequest\x1a'.mnemonas.dataplane.v1.GetChunkResponse\x12[\n" +
	"\bHasChunk\x12&.mnemonas.dataplane.v1.HasChunkRequest\x1a'.mnemonas.dataplane.v1.HasChunkResponse\x12d\n" +
	"\vDeleteChunk\x12).mnemonas.dataplane.v1.DeleteChunkRequest\x1a*.mnemonas.dataplane.v1.DeleteChunkResponse\x12Z\n" +
	"\aPutFile\x12%.mnemonas.dataplane.v1.PutFileRequest\x1a&.mnemonas.dataplane.v1.PutFileResponse(\x01\x12Z\n" +
	"\aGetFile\x12%.mnemonas.dataplane.v1.GetFileRequest\x1a&.mnemonas.dataplane.v1.GetFileResponse0\x01\x12U\n" +
	"\x06Health\x12$.mnemonas.dataplane.v1.HealthRequest\x1a%.mnemonas.dataplane.v1.HealthResponse\x12R\n" +
	"\x05Stats\x12#.mnemonas.dataplane.v1.StatsRequest\x1a$.mnemonas.dataplane.v1.StatsResponse\x12R\n" +
	"\x05Scrub\x12#.mnemonas.dataplane.v1.ScrubRequest\x1a$.mnemonas.dataplane.v1.ScrubResponse\x12d\n" +
	"\vListObjects\x12).mnemonas.dataplane.v1.ListObjectsRequest\x1a*.mnemonas.dataplane.v1.ListObjectsResponseB3Z1github.com/seanbao/mnemonas/internal/dataplane/v1b\x06proto3"

var (
	file_proto_dataplane_proto_rawDescOnce sync.Once
	file_proto_dataplane_proto_rawDescData []byte
)

func file_proto_dataplane_proto_rawDescGZIP() []byte {
	file_proto_dataplane_proto_rawDescOnce.Do(func() {
		file_proto_dataplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dataplane_proto_rawDesc), len(file_proto_dataplane_proto_rawDesc)))
	})
	return file_proto_dataplane_proto_rawDescData
}

var file_proto_dataplane_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_dataplane_proto_goTypes = []any{
	(*PutChunkRequest)(nil),     // 0: mnemonas.dataplane.v1.PutChunkRequest
	(*PutChunkResponse)(nil),    // 1: mnemonas.dataplane.v1.PutChunkResponse
	(*GetChunkRequest)(nil),     // 2: mnemonas.dataplane.v1.GetChunkRequest
	(*GetChunkResponse)(nil),    // 3: mnemonas.dataplane.v1.GetChunkResponse
	(*HasChunkRequest)(nil),     // 4: mnemonas.dataplane.v1.HasChunkRequest
	(*HasChunkResponse)(nil),    // 5: mnemonas.dataplane.v1.HasChunkResponse
	(*DeleteChunkRequest)(nil),  // 6: mnemonas.dataplane.v1.DeleteChunkRequest
	(*DeleteChunkResponse)(nil), // 7: mnemonas.dataplane.v1.DeleteChunkResponse
	(*PutFileRequest)(nil),      // 8: mnemonas.dataplane.v1.PutFileRequest
	(*FileMetadata)(nil),        // 9: mnemonas.dataplane.v1.FileMetadata
	(*PutFileResponse)(nil),     // 10: mnemonas.dataplane.v1.PutFileResponse
	(*GetFileRequest)(nil),      // 11: mnemonas.dataplane.v1.GetFileRequest
	(*GetFileResponse)(nil),     // 12: mnemonas.dataplane.v1.GetFileResponse
	(*HealthRequest)(nil),       // 13: mnemonas.dataplane.v1.HealthRequest
	(*HealthResponse)(nil),      // 14: mnemonas.dataplane.v1.HealthResponse
	(*StatsRequest)(nil),        // 15: mnemonas.dataplane.v1.StatsRequest
	(*StatsResponse)(nil),       // 16: mnemonas.dataplane.v1.StatsResponse
	(*ScrubRequest)(nil),        // 17: mnemonas.dataplane.v1.ScrubRequest
	(*ScrubResponse)(nil),       // 18: mnemonas.dataplane.v1.ScrubResponse
	(*ScrubError)(nil),          // 19: mnemonas.dataplane.v1.ScrubError
	(*ListObjectsRequest)(nil),  // 20: mnemonas.dataplane.v1.ListObjectsRequest
	(*ListObjectsResponse)(nil), // 21: mnemonas.dataplane.v1.ListObjectsResponse
	(*ObjectInfo)(nil),          // 22: mnemonas.dataplane.v1.ObjectInfo
}
var file_proto_dataplane_proto_depIdxs = []int32{
	9,  // 0: mnemonas.dataplane.v1.PutFileRequest.metadata:type_name -> mnemonas.dataplane.v1.FileMetadata
	19, // 1: mnemonas.dataplane.v1.ScrubResponse.errors:type_name -> mnemonas.dataplane.v1.ScrubError
	22, // 2: mnemonas.dataplane.v1.ListObjectsResponse.objects:type_name -> mnemonas.dataplane.v1.ObjectInfo
	0,  // 3: mnemonas.dataplane.v1.DataPlane.PutChunk:input_type -> mnemonas.dataplane.v1.PutChunkRequest
	2,  // 4: mnemonas.dataplane.v1.DataPlane.GetChunk:input_type -> mnemonas.dataplane.v1.GetChunkRequest
	4,  // 5: mnemonas.dataplane.v1.DataPlane.HasChunk:input_type -> mnemonas.dataplane.v1.HasChunkRequest
	6,  // 6: mnemonas.dataplane.v1.DataPlane.DeleteChunk:input_type -> mnemonas.dataplane.v1.DeleteChunkRequest
	8,  // 7: mnemonas.dataplane.v1.DataPlane.PutFile:input_type -> mnemonas.dataplane.v1.PutFileRequest
	11, // 8: mnemonas.dataplane.v1.DataPlane.GetFile:input_type -> mnemonas.dataplane.v1.GetFileRequest
	13, // 9: mnemonas.dataplane.v1.DataPlane.Health:input_type -> mnemonas.dataplane.v1.HealthRequest
	15, // 10: mnemonas.dataplane.v1.DataPlane.Stats:input_type -> mnemonas.dataplane.v1.StatsRequest
	17, // 11: mnemonas.dataplane.v1.DataPlane.Scrub:input_type -> mnemonas.dataplane.v1.ScrubRequest
	20, // 12: mnemonas.dataplane.v1.DataPlane.ListObjects:input_type -> mnemonas.dataplane.v1.ListObjectsRequest
	1,  // 13: mnemonas.dataplane.v1.DataPlane.PutChunk:output_type -> mnemonas.dataplane.v1.PutChunkResponse
	3,  // 14: mnemonas.dataplane.v1.DataPlane.GetChunk:output_type -> mnemonas.dataplane.v1.GetChunkResponse
	5,  // 15: mnemonas.dataplane.v1.DataPlane.HasChunk:output_type -> mnemonas.dataplane.v1.HasChunkResponse
	7,  // 16: mnemonas.dataplane.v1.DataPlane.DeleteChunk:output_type -> mnemonas.dataplane.v1.DeleteChunkResponse
	10, // 17: mnemonas.dataplane.v1.DataPlane.PutFile:output_type -> mnemonas.dataplane.v1.PutFileResponse
	12, // 18: mnemonas.dataplane.v1.DataPlane.GetFile:output_type -> mnemonas.dataplane.v1.GetFileResponse
	14, // 19: mnemonas.dataplane.v1.DataPlane.Health:output_type -> mnemonas.dataplane.v1.HealthResponse
	16, // 20: mnemonas.dataplane.v1.DataPlane.Stats:output_type -> mnemonas.dataplane.v1.StatsResponse
	18, // 21: mnemonas.dataplane.v1.DataPlane.Scrub:output_type -> mnemonas.dataplane.v1.ScrubResponse
	21, // 22: mnemonas.dataplane.v1.DataPlane.ListObjects:output_type -> mnemonas.dataplane.v1.ListObjectsResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_dataplane_proto_init() }
func file_proto_dataplane_proto_init() {
	if File_proto_dataplane_proto != nil {
		return
	}
	file_proto_dataplane_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_dataplane_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_dataplane_proto_msgTypes[8].OneofWrappers = []any{
		(*PutFileRequest_Metadata)(nil),
		(*PutFileRequest_Chunk)(nil),
	}
	file_proto_dataplane_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_dataplane_proto_msgTypes[20].OneofWrappers = []any{}
	file_proto_dataplane_proto_msgTypes[21].OneofWrappers = []any{}
	file_proto_dataplane_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dataplane_proto_rawDesc), len(file_proto_dataplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dataplane_proto_goTypes,
		DependencyIndexes: file_proto_dataplane_proto_depIdxs,
		MessageInfos:      file_proto_dataplane_proto_msgTypes,
	}.Build()
	File_proto_dataplane_proto = out.File
	file_proto_dataplane_proto_goTypes = nil
	file_proto_dataplane_proto_depIdxs = nil
}
