// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.1
// source: proto/dataplane.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataPlane_PutChunk_FullMethodName    = "/mnemonas.dataplane.v1.DataPlane/PutChunk"
	DataPlane_GetChunk_FullMethodName    = "/mnemonas.dataplane.v1.DataPlane/GetChunk"
	DataPlane_HasChunk_FullMethodName    = "/mnemonas.dataplane.v1.DataPlane/HasChunk"
	DataPlane_DeleteChunk_FullMethodName = "/mnemonas.dataplane.v1.DataPlane/DeleteChunk"
	DataPlane_PutFile_FullMethodName     = "/mnemonas.dataplane.v1.DataPlane/PutFile"
	DataPlane_GetFile_FullMethodName     = "/mnemonas.dataplane.v1.DataPlane/GetFile"
	DataPlane_Health_FullMethodName      = "/mnemonas.dataplane.v1.DataPlane/Health"
	DataPlane_Stats_FullMethodName       = "/mnemonas.dataplane.v1.DataPlane/Stats"
	DataPlane_Scrub_FullMethodName       = "/mnemonas.dataplane.v1.DataPlane/Scrub"
	DataPlane_ListObjects_FullMethodName = "/mnemonas.dataplane.v1.DataPlane/ListObjects"
)

// DataPlaneClient is the client API for DataPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataPlane service - Go control plane calls Rust data plane
type DataPlaneClient interface {
	// Store data chunk, returns CAS address
	PutChunk(ctx context.Context, in *PutChunkRequest, opts ...grpc.CallOption) (*PutChunkResponse, error)
	// Get data chunk
	GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkResponse, error)
	// Check if data chunk exists
	HasChunk(ctx context.Context, in *HasChunkRequest, opts ...grpc.CallOption) (*HasChunkResponse, error)
	// Delete data chunk (GC mark)
	DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error)
	// Store file (CDC split + store)
	PutFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutFileRequest, PutFileResponse], error)
	// Get file
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetFileResponse], error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Get storage statistics
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Run scrub to verify data integrity
	Scrub(ctx context.Context, in *ScrubRequest, opts ...grpc.CallOption) (*ScrubResponse, error)
	// List all object hashes (for GC)
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
}

type dataPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewDataPlaneClient(cc grpc.ClientConnInterface) DataPlaneClient {
	return &dataPlaneClient{cc}
}

func (c *dataPlaneClient) PutChunk(ctx context.Context, in *PutChunkRequest, opts ...grpc.CallOption) (*PutChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutChunkResponse)
	err := c.cc.Invoke(ctx, DataPlane_PutChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (*GetChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChunkResponse)
	err := c.cc.Invoke(ctx, DataPlane_GetChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) HasChunk(ctx context.Context, in *HasChunkRequest, opts ...grpc.CallOption) (*HasChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasChunkResponse)
	err := c.cc.Invoke(ctx, DataPlane_HasChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) DeleteChunk(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChunkResponse)
	err := c.cc.Invoke(ctx, DataPlane_DeleteChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) PutFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutFileRequest, PutFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlane_ServiceDesc.Streams[0], DataPlane_PutFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutFileRequest, PutFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_PutFileClient = grpc.ClientStreamingClient[PutFileRequest, PutFileResponse]

func (c *dataPlaneClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataPlane_ServiceDesc.Streams[1], DataPlane_GetFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetFileRequest, GetFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_GetFileClient = grpc.ServerStreamingClient[GetFileResponse]

func (c *dataPlaneClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DataPlane_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, DataPlane_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) Scrub(ctx context.Context, in *ScrubRequest, opts ...grpc.CallOption) (*ScrubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrubResponse)
	err := c.cc.Invoke(ctx, DataPlane_Scrub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataPlaneClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, DataPlane_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataPlaneServer is the server API for DataPlane service.
// All implementations must embed UnimplementedDataPlaneServer
// for forward compatibility.
//
// DataPlane service - Go control plane calls Rust data plane
type DataPlaneServer interface {
	// Store data chunk, returns CAS address
	PutChunk(context.Context, *PutChunkRequest) (*PutChunkResponse, error)
	// Get data chunk
	GetChunk(context.Context, *GetChunkRequest) (*GetChunkResponse, error)
	// Check if data chunk exists
	HasChunk(context.Context, *HasChunkRequest) (*HasChunkResponse, error)
	// Delete data chunk (GC mark)
	DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error)
	// Store file (CDC split + store)
	PutFile(grpc.ClientStreamingServer[PutFileRequest, PutFileResponse]) error
	// Get file
	GetFile(*GetFileRequest, grpc.ServerStreamingServer[GetFileResponse]) error
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Get storage statistics
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Run scrub to verify data integrity
	Scrub(context.Context, *ScrubRequest) (*ScrubResponse, error)
	// List all object hashes (for GC)
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	mustEmbedUnimplementedDataPlaneServer()
}

// UnimplementedDataPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataPlaneServer struct{}

func (UnimplementedDataPlaneServer) PutChunk(context.Context, *PutChunkRequest) (*PutChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutChunk not implemented")
}
func (UnimplementedDataPlaneServer) GetChunk(context.Context, *GetChunkRequest) (*GetChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedDataPlaneServer) HasChunk(context.Context, *HasChunkRequest) (*HasChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasChunk not implemented")
}
func (UnimplementedDataPlaneServer) DeleteChunk(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChunk not implemented")
}
func (UnimplementedDataPlaneServer) PutFile(grpc.ClientStreamingServer[PutFileRequest, PutFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PutFile not implemented")
}
func (UnimplementedDataPlaneServer) GetFile(*GetFileRequest, grpc.ServerStreamingServer[GetFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedDataPlaneServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDataPlaneServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedDataPlaneServer) Scrub(context.Context, *ScrubRequest) (*ScrubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scrub not implemented")
}
func (UnimplementedDataPlaneServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedDataPlaneServer) mustEmbedUnimplementedDataPlaneServer() {}
func (UnimplementedDataPlaneServer) testEmbeddedByValue()                   {}

// UnsafeDataPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataPlaneServer will
// result in compilation errors.
type UnsafeDataPlaneServer interface {
	mustEmbedUnimplementedDataPlaneServer()
}

func RegisterDataPlaneServer(s grpc.ServiceRegistrar, srv DataPlaneServer) {
	// If the following call pancis, it indicates UnimplementedDataPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataPlane_ServiceDesc, srv)
}

func _DataPlane_PutChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).PutChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_PutChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).PutChunk(ctx, req.(*PutChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_GetChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).GetChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_GetChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).GetChunk(ctx, req.(*GetChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_HasChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).HasChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_HasChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).HasChunk(ctx, req.(*HasChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_DeleteChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).DeleteChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_DeleteChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).DeleteChunk(ctx, req.(*DeleteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_PutFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataPlaneServer).PutFile(&grpc.GenericServerStream[PutFileRequest, PutFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_PutFileServer = grpc.ClientStreamingServer[PutFileRequest, PutFileResponse]

func _DataPlane_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataPlaneServer).GetFile(m, &grpc.GenericServerStream[GetFileRequest, GetFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataPlane_GetFileServer = grpc.ServerStreamingServer[GetFileResponse]

func _DataPlane_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_Scrub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).Scrub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_Scrub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).Scrub(ctx, req.(*ScrubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataPlane_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataPlaneServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataPlane_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataPlaneServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataPlane_ServiceDesc is the grpc.ServiceDesc for DataPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mnemonas.dataplane.v1.DataPlane",
	HandlerType: (*DataPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutChunk",
			Handler:    _DataPlane_PutChunk_Handler,
		},
		{
			MethodName: "GetChunk",
			Handler:    _DataPlane_GetChunk_Handler,
		},
		{
			MethodName: "HasChunk",
			Handler:    _DataPlane_HasChunk_Handler,
		},
		{
			MethodName: "DeleteChunk",
			Handler:    _DataPlane_DeleteChunk_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DataPlane_Health_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _DataPlane_Stats_Handler,
		},
		{
			MethodName: "Scrub",
			Handler:    _DataPlane_Scrub_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _DataPlane_ListObjects_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutFile",
			Handler:       _DataPlane_PutFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetFile",
			Handler:       _DataPlane_GetFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/dataplane.proto",
}
