export { DashboardPage } from './Dashboard'
export { FilesPage } from './Files'
export { AlbumPage } from './Album'
export { VersionsPage } from './Versions'
export { TrashPage } from './Trash'
export { StoragePage } from './Storage'
export { HealthPage } from './Health'
export { default as MaintenancePage } from './Maintenance'
export { SettingsPage } from './Settings'
export { NotFoundPage } from './NotFound'
